#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : opcodes
Version  : 0.3.14
Release  : 9
URL      : https://files.pythonhosted.org/packages/df/2d/4d98a725b5e73ba3d8588fd415cc64120182ebec78e0695ecae7408a2d74/opcodes-0.3.14.tar.gz
Source0  : https://files.pythonhosted.org/packages/df/2d/4d98a725b5e73ba3d8588fd415cc64120182ebec78e0695ecae7408a2d74/opcodes-0.3.14.tar.gz
Summary  : Database of Processor Instructions/Opcodes
Group    : Development/Tools
License  : BSD-2-Clause
Requires: opcodes-license = %{version}-%{release}
Requires: opcodes-python = %{version}-%{release}
Requires: opcodes-python3 = %{version}-%{release}
Requires: setuptools
BuildRequires : buildreq-distutils3
BuildRequires : setuptools

%description
.. image:: https://img.shields.io/github/license/Maratyszcza/Opcodes.svg
   :alt: License
   :target: https://github.com/Maratyszcza/Opcodes/blob/master/license.rst

.. image:: https://img.shields.io/pypi/v/opcodes.svg
   :alt: PyPI Package
   :target: https://pypi.python.org/pypi/opcodes

.. image:: https://readthedocs.org/projects/opcodes/badge/?style
   :alt: Documentation
   :target: https://opcodes.readthedocs.org

.. image:: https://img.shields.io/travis/Maratyszcza/Opcodes.svg
   :alt: Test Status
   :target: https://travis-ci.org/Maratyszcza/Opcodes

Opcodes Project
===============

The goal of this project is to document instruction sets in a format convenient for tools development. An instruction set is represented by three files:

- An XML file that describes instructions
- An XSD file that describes the structure of the XML file
- A Python module that reads the XML file and represents it as a set of Python objects

This project is a spin-off from `PeachPy <https://github.com/Maratyszcza/PeachPy>`_ assembler.

Current status
--------------

The project provides descriptions for most user-mode x86, x86-64, and k1om instructions up to AVX-512 and SHA (including 3dnow!+, XOP, FMA3, FMA4, TBM and BMI2). The following instructions are currently **NOT** supported:

- All priveledged instructions and user-mode system instructions (e.g. XSAVE, SLDT)
- Legacy string/streaming instructions (MOVS/SCAS/CMPS/STOS/LODS)
- LOCK and REP/REPZ/REPNZ prefixes
- x87 FPU instructions
- VIA Padlock instructions
- Intel HTM instructions

For each instruction the following information is provided:

- Summary description
- Instruction names in Intel assembly (`PeachPy <https://github.com/Maratyszcza/PeachPy>`_, `NASM <http://nasm.us>`_, `YASM <http://yasm.tortall.net>`_ and MASM assemblers), AT&T assembly (GNU assembler) and Plan 9 assembly (`Go <https://golang.org>`_ assembler)
- Operand types and characteristics (whether the operand is input or output)
- Implicit input and output registers
- ISA where this instruction was introduced
- Whether the instruction operates on FPU or MMX state
- Whether the instruction operates on AVX or legacy SSE state
- Whether the instruction has no dependency on input values when input operands refer to the same register (e.g. `XOR eax, eax` has no dependency on `eax`)
- Whether the instruction is supported by Native Client validator and when the support was introduced
- Whether the instruction that writes to a 32-bit register is recognized by x86-64 Native Client validator as zero-extending

Installation
------------

.. code-block:: bash

  pip install --upgrade Opcodes

Users
-----

- `PeachPy <https://github.com/Maratyszcza/PeachPy>`_ -- x86-64 assembler embedded in Python that targets High-Performance Computing use-cases.

- `Template-Assembly <https://github.com/mattbierner/Template-Assembly>`_ -- Embedding x86 assembly code in C++ with metaprogramming using a domain specific language.

Peer-Reviewed Publications
--------------------------

- Marat Dukhan "PeachPy meets Opcodes: Direct Machine Code Generation from Python", Python for High-Performance Computing (PyHPC) 2015 (`slides <http://www.peachpy.io/slides/pyhpc2015>`_, `paper on ACM Digital Library <https://dl.acm.org/citation.cfm?id=2835860>`_).

Acknowledgements
----------------

.. image:: https://github.com/Maratyszcza/PeachPy/blob/master/logo/hpcgarage.png
  :alt: HPC Garage logo
  :target: http://hpcgarage.org/

.. image:: https://github.com/Maratyszcza/PeachPy/blob/master/logo/college-of-computing.gif
  :alt: Georgia Tech College of Computing logo
  :target: http://www.cse.gatech.edu/

This work is a research project at the HPC Garage lab in the Georgia Institute of Technology, College of Computing, School of Computational Science and Engineering.

The work was supported in part by grants to Prof. Richard Vuduc's research lab, `The HPC Garage <www.hpcgarage.org>`_, from the National Science Foundation (NSF) under NSF CAREER award number 0953100; and a grant from the Defense Advanced Research Projects Agency (DARPA) Computer Science Study Group program

Any opinions, conclusions or recommendations expressed in this software and documentation are those of the authors and not necessarily reflect those of NSF or DARPA.

%package license
Summary: license components for the opcodes package.
Group: Default

%description license
license components for the opcodes package.


%package python
Summary: python components for the opcodes package.
Group: Default
Requires: opcodes-python3 = %{version}-%{release}

%description python
python components for the opcodes package.


%package python3
Summary: python3 components for the opcodes package.
Group: Default
Requires: python3-core
Provides: pypi(opcodes)

%description python3
python3 components for the opcodes package.


%prep
%setup -q -n opcodes-0.3.14
cd %{_builddir}/opcodes-0.3.14

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583189157
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/opcodes
cp %{_builddir}/opcodes-0.3.14/license.rst %{buildroot}/usr/share/package-licenses/opcodes/75becd65c0fb973ddc34dd97fb419826c1c1183a
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/opcodes/75becd65c0fb973ddc34dd97fb419826c1c1183a

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
